### ISSUE TITLE
Exit code when trying to create an already existing checkpoint

### ISSUE THREAD

**Issue by ferki** [melezhik/sparrow#1]
`sparrow check add $project $checkname` currently returns with error when the `$checkname` already exists indide `$project`.

Since this will result in the expected state anyway, it might be a good idea to return success and and exit code of 0 instead (as discussed via IRC and/or RexOps/rex-recipes#28).

**Comment by melezhik** [comment]
done in version 0.0.21 - uploaded to CPAN - https://metacpan.org/release/MELEZHIK/Sparrow-0.0.21
