### ISSUE TITLE
plg man for private plugins

### ISSUE THREAD

**Issue by spigell** [melezhik/sparrow#10]
Здравствуйте. Я через sparrow.list добавил и установил приватный плагин.
```
[spigell@puppet_sparrow-test sshuttle]$ sparrow plg list user-spigell-dev
[installed sparrow plugins]

[public]

user


[private]

user-spigell-dev

```

Но дока все равно берется не из того каталога.
```
[spigell@puppet_sparrow-test sshuttle]$ sparrow plg man user-spigell-dev
cat: /home/spigell/sparrow/plugins/public/user-spigell-dev/README.md: No such file or directory
```
Взгляните, как будет время.
Спасибо.

**Comment by melezhik** [comment]
Приветствую! Для приватных плагинов команда sparrow plg man не работает. Если вас интересует именно это, то оставьте тикет открытым, реализую позже.

**Comment by melezhik** [comment]
Попробуйте поставить Sparrow с этого коммита, док-я для приватных плагинов должна показываться

**Comment by spigell** [comment]
Спасибо. Работает.
