### ISSUE TITLE
dependencies for bash and python plugins.

### ISSUE THREAD

**Issue by spigell** [melezhik/sparrow#12]
Здравствуйте. Насколько я понимаю, для перла и руби есть в sparrow сделана поддержка для файлов cpanfile и gemfile. У  питона так же есть [https://en.wikipedia.org/wiki/Pip_(package_manager)](pip), с помощью которого можно было бы устанавливать зависимости. К сожалению, он далеко не во все пакеты python включен, к примеру на centos7 он не ставится вместе с питоном. 

Также, можно было бы сделать что-то подобное для bash плагинов через плагин package-generic. Конечно, минус в том, что плагин мало ОС поддерживает.

Как вы считаете?

**Comment by melezhik** [comment]
Приветствую! Можно подумать что бы добавить поддержку pip/requirements.txt но насколько я понимаю, что бы сделать все полностью изолировано ( в стиле cpanfile,carton/rubygems,bundler) нужно еще добавить запуск через virtualenv , по крайней мере эта то, что было актуально несколько лет назад, когда я занимался деплойментом питон приложений, возможно к это времени появилось что-то новое ... Может вы знаете какие-то варианты или сделаете исследование?

Насчет зависимостей для bash , я вас не очень понял, как вы это видите?

**Comment by spigell** [comment]
Вроде бы ничего новее virtualenv не было сделано. Я поищу информацию. 

Баш скрипты полагаются на какие-либо утилиты. И не всегда они установлены в системе. Можно было бы сделать какой-нибудь файлик dependencies.txt, где будет указан хотя бы пакет, который нужен для этого плагина. Эти пакеты можно было бы ставить с помощью package-generic. Конечно, есть некоторые трудности в таком подходе. Я вижу две: сам плагин должен поддерживать много разных ос и названия пакетов в различных ос может отличаться.

**Comment by melezhik** [comment]
> Я вижу две: сам плагин должен поддерживать много разных ос и названия пакетов в различных ос может отличаться.

Да, если поддержка разных os в плагине package-generic несложна, то разница в названиях самих пакетов - действительно проблема, вам придется поддерживать разные списки и как-то их проталкивать в плагин package-generic   

А почему вы не хотите решить это все на уровне sparrowdo? Там это сделать проще, вот пример: 

```
$ cat sparrowfile 

 if target_os() ~~ m/centos/ {

    task_run  %(
      task => 'install foo-centos package',
      plugin => 'package-generic',
      parameters => %( list => 'foo-centos' )
    );
  
}

 if target_os() ~~ m/debian/ {

    task_run  %(
      task => 'install foo-debian package',
      plugin => 'package-generic',
      parameters => %( list => 'foo-debian' )
    );
  
}

# ну и так далее
```

Код конечно же может быть более элегантным и компактным, с использованием `case` или тернарных каких нибудь операторов или же словарей ( хэшей ), но идея, надеюсь, ясна ... ?

**Comment by melezhik** [comment]
> Вроде бы ничего новее virtualenv не было сделано. Я поищу информацию.

ok

**Comment by spigell** [comment]
> А почему вы не хотите решить это все на уровне sparrowdo?

Не совсем понял к чему здесь sparrowdo. Мы сейчас говорим о ситуации only-sparrow, как о менеджере скриптов. 
Давайте пока про bash плагины оставим. Делать аналогию с cpanfile и другими пока видется не очень простой. 
Пока я нашел один проект по управлению shell скриптов - https://github.com/bpkg/bpkg. Там есть раздел про зависимости. Я еще попробую его посмотреть.

**Comment by melezhik** [comment]
Да, я вас понял. Давайте еще раз спрошу. Вы под зависимостями для bash понимаете системные пакеты?

**Comment by spigell** [comment]
Да, под зависимостями для bash плагинов я имею ввиду системные пакеты.

**Comment by melezhik** [comment]
Тогда не очень понимаю, чем не подходит package-generic для этого? приведите примеры того, как вы это видите?

**Comment by spigell** [comment]
Подходит, но с ограничениями. Мы выше это обсуждали:

> Я вижу две: сам плагин должен поддерживать много разных ос и названия пакетов в различных ос может отличаться.

Вариант со sparrowdo я не рассматриваю, так как это полноценный configuration manager, на мой взгляд это перебор.

Я вижу это так:
Есть файлик в корне плагина - dependencies.txt. В нем описаны пакеты, которые должны быть установлены, чтобы плагин работал корректно. 
Когда запускается установка плагина через sparrow plg install, то менеджер смотрит на этот файлик и устанавливает эти пакеты через package-generic.

**Comment by melezhik** [comment]
Да, я вас понял ... а что если нам сделать все это через package-generic, расширив его функциональность понятием дистрибутива os  ? Вот как можно было бы:

```
$ sparrow project create packages
$ sparrow task add package apache package-generic
$ sparrow task ini packages/apache
<os>
 <debian>
    apache2
 </debian>
 <centos>
    httpd 
    mod_ssl
 </centos>
</os>

$ sparrow task run packages/apache
```

Что думаете?

**Comment by melezhik** [comment]
еще раз перечитал ...

> Есть файлик в корне плагина - dependencies.txt. В нем описаны пакеты, которые должны быть установлены, чтобы плагин работал корректно.
Когда запускается установка плагина через sparrow plg install, то менеджер смотрит на этот файлик и устанавливает эти пакеты через package-generic.


да я понял, вы хотите более системное решение .... тут нужно думать ... а вы пока подумайте над моей альтернативой ...

**Comment by spigell** [comment]
> а вы пока подумайте над моей альтернативой ...

А эту задачу sparrow будет создавать? Было бы неплохо, если так. Т.е. сам разработчик плагина писал бы конфиг, это да, а при установке создавалась таска для установки пакетов.

**Comment by melezhik** [comment]
много думал над вашим предложение и все же склоняюсь к тому, что бы установку зависимостей по системным пакетам делать стороними инструментами ( наприер, как я предложил через sparrow tasks ).

Если идти предложенным вами путем мне придется делать процесс установки sparrow плагинов зависимым от плагина sparrow package-generic, а sparrow изначально спроектирован так, что плагины не зависят друг от друга, это деалает всю систему очень простой и надежной.

Насколько для вас критична данная фича? Почему вы не хотите использовать механизм sparrow tasks? Мне кажется он хорошо подходит под решение данной проблемы.

**Comment by spigell** [comment]
Эта фича некритична, но она бы привела установку bash зависимостей (системных пакетов) к одному виду с другими языками. Мне думается, sparrow tasks тут излишни. Я так понимаю, это необходимо будет делать пользователю, который этот плагин устанавливает? Лучше использовать sparrow box. То есть делать так:
```
cat pre-install.json
[

  {
    "task" : "pre install box for plg sshuttle",
    "plugin" : "package-generic",
    "data" : {
      "list" : "sshuttle"
    }
  },
  {
/// Another task
    }
  }

]
```
sparrow box run pre-install.json
Да, сейчас вижу, что вкручивать плагин внутрь sparrow не очень хорошая идея. 
Но фича с расширением функционала package-generic для разных названий пакетов была бы неплоха.

--- 
С питоном все еще разбираюсь.

**Comment by melezhik** [comment]
Ок , тогда в рамках этого тикета реализую заявленную функциональность для плагина package-generic. Если что-то нужно будет ещё - пишите сюда же.

**Comment by spigell** [comment]
Здравствуйте. Касательно питона. Можно поступить очень просто, добавив в переменную `PYTHONPATH` какой-нибудь каталог с необходимыми модулями, куда pip будет устанавливать зависимости. То есть, по аналогии с [этим](https://github.com/melezhik/sparrow/blob/f2c6a4a00c3c9e22e3fa93c20f0c5df0e2b80e98/lib/Sparrow/Commands/Plugin.pm#L145-L147) :

```
                if ( -f sparrow_root."/plugins/public/$pid/requirements.txt" ){
                  execute_shell_command("cd ".sparrow_root."/plugins/public/$pid && pip install -t  lib");
} 

```

А при запуске плагина

```
    if (-f project_root_dir()."/requirements.txt" ){
my $python_additional_lib_dir = project_root_dir()./lib
my $cmd = "PYTHONPATH=\$PYTHONPATH:".(story_cache_dir()).":$python_lib_dir:+:project_root_dir()./lib python $file";
```

Я написал это условно, конечно. По крайней мере, такой подход у меня стабильно работает, когда я запускаю плагины через strun:

```
$ strun 
• at 2017-04-11 22:07:07

Traceback (most recent call last):
  File "/home/test/story.py", line 2, in <module>
    from pyzabbix import ZabbixAPI
ImportError: No module named pyzabbix

[duty-shark ~]$ pip install -t lib pyzabbix
Collecting pyzabbix
  Using cached pyzabbix-0.7.4.tar.gz
Collecting requests>=1.0 (from pyzabbix)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Installing collected packages: requests, pyzabbix
  Running setup.py install for pyzabbix ... done
Successfully installed pyzabbix-0.7.4 requests-2.13.0


[duty-shark ~]$ export PYTHONPATH="$PYTHONPATH:+:./lib" ; strun --param host="http://127.0.0.1:8080" --param user="test" --param password="test" --param output=stdout  
• at 2017-04-11 22:11:11

127.0.0.1 zabbix

ok	scenario succeeded
STATUS	SUCCEED

```
Конечно, это не решает проблему с разным питоном на станциях.

**Comment by spigell** [comment]
Также, можно воспользоваться [pyenv](https://github.com/pyenv/pyenv) вместе c [pundle](https://github.com/Deepwalker/pundler), [Хабр](https://habrahabr.ru/post/249425/) для установки модулей и смены окружения, но, на мой взгляд, они больше для разработки, чем для деплоя/запуска. Я их немного попробовал, очень удобно, да, но опять-таки, слишком много надо тащить в sparrow, чтобы с ним заработало, как мне кажется. 

По сути это тот же virtualenv с его activate/deactivate, но в профиль.

Что думаете?

**Comment by melezhik** [comment]
Здравствуйте,  посмотрю завтра ваши ссылки и постараюсь ответить.

**Comment by melezhik** [comment]
Посмотрел ( сильно правда не вникал ), первая мысль такая, как можно сделать:

При установке sparrow плагина, добавляем внутри sparrow обработчик python pависимостей, если они есть:

`pip install -t $plg-install-directory/python-lib $python-module` где $plg-install-directory - директория в которую ставится плагин

Далее, внутри sparrow при запуске плагина, "цепляем" папку с зависимостями:

`export PYTHONPATH="$PYTHONPATH:$plg-install-directory/python-lib/lib`
 
Все это можно реализовать внутри sparrow. Исходим из того, что pip должен быть установлен в системе.

На мой взгляд, пока это самое простое и лекго реализуемое решение, можно начать с него, и если оно нас по каким-то причинам в будущем не устроит, можем рассмотреть другие варианты ... Что думаете?

**Comment by spigell** [comment]
Здравствуйте. Да, давайте этот вариант.

**Comment by melezhik** [comment]
Попробуйте обновить sparrow из git. Далее объявляйте зависимости в файле requirements.txt в формате https://pip.pypa.io/en/stable/user_guide/#requirements-files 

Пример плагина - https://github.com/melezhik/python-sparrow-plugin

**Comment by melezhik** [comment]
https://sparrowdo.wordpress.com/2017/05/12/using-python-dependencies-in-sparrow-plugins/

**Comment by spigell** [comment]
Да, все работает. Спасибо.

**Comment by melezhik** [comment]
https://metacpan.org/release/MELEZHIK/Sparrow-0.2.37 released

**Comment by spigell** [comment]
А вот это планируете делать? 
https://github.com/melezhik/sparrow/issues/12#issuecomment-289993067

**Comment by melezhik** [comment]
Я правильно понимаю, вы про это? 

Расширить функциональность  package-generic понятием дистрибутива os :
```
$ sparrow project create packages
$ sparrow task add package apache package-generic
$ sparrow task ini packages/apache
<os>
 <debian>
    apache2
 </debian>
 <centos>
    httpd 
    mod_ssl
 </centos>
</os>

$ sparrow task run packages/apache
```

**Comment by spigell** [comment]
Я про это, да.

**Comment by melezhik** [comment]
буду делать отдельным тикетом - https://github.com/melezhik/package-generic/issues/1 , думаю не займет много времени ...
