### ISSUE TITLE
--silent or --quiet flag for all sparrow command

### ISSUE THREAD

**Issue by spigell** [melezhik/sparrow#13]
Здравствуйте. Иногда мне приходится парсить вывод из sparrow плагина. И также приходится отбрасывать последние строчки через sed. Неплохо было бы, если имелась возможность убирать строчки от sparrow о том. что все успешно/неуспешно.
То есть, запуская плагин с этим флагом, я хочу видеть только то, что выводит сам скрипт. Например,
```
[spigell@hammerhead ~]$ sparrow plg run bash --param command='"echo This is OUTPUT"'
{bash}
@ runs bash command

{bash} modules/bash-command/ params: envvars: at 2017-03-26 18:30:12
This is OUTPUT
ok	scenario succeeded
STATUS	SUCCEED
```
Тоже самое, но с этим флагом.
```
[spigell@hammerhead ~]$ sparrow plg run bash --param command='"echo This is OUTPUT"' --quiet

This is OUTPUT

```
Я честно не знаю как его назвать. Ведь у strun есть --silent, а у sparrow task есть --quiet
Да, я понимаю, что c этим флагом скорее всего не могут быть произведены проверки через файл story.check

Как вы считаете?

**Comment by melezhik** [comment]
Здравствуйте ! Идея понятна. Можно было бы добавить это в текущую реализацию флага  silent, но вот что делать, если при выполнении плагина будут ошибки , например ненулевой код заверешения сценария истории или ошибки валидация в проверочном файле , то в этом случае что делать ? Выводить сообщения об ошибках или нет ?

**Comment by spigell** [comment]
Мне кажется, для простоты, даже при ошибках не надо ничего выводить. 
Возможно, в будущем, если надо будет, то можно сделать флаг --show-errors, который будет применятся вместе с первым, чтобы выводить ошибки, если они произойдут.

**Comment by melezhik** [comment]
Ок, я думаю я добавлю отдельную опцию запуска sparrow клиента --format $format которая будет настраивать вид отчёта. Например для случая можно было бы сказать так : 

    --format concise # сжатый формат , не ввыводить служебные сообщения sparrow ...

Что думаете ?

**Comment by spigell** [comment]
Да, так будет неплохо.

**Comment by melezhik** [comment]
Попробуйте.

```
$ sparrowdo --module_run=Sparrow::Update ...
# или
$ cpanm https://github.com/melezhik/outthentic.git 
$ cpanm https://github.com/melezhik/sparrow.git
```

Далее : 

```
$ sparrow plg run df-check --format concise
$ sparrow task run disk/check --format concise
$ sparrow box run /path/to/box.json --format concise
```

**Comment by spigell** [comment]
Попробовал. Насколько я понял, этот режим немного сжимаете вывод, но не полностью. Планируется ли еще тип формата, кроме default и concise?

**Comment by melezhik** [comment]
Напишите , что бы вы хотели ещё убрать. Может быть в этом формате сделаем.

**Comment by spigell** [comment]
Как стало.
```
[spigell@dev1 ~]$ sparrow plg run bash --param command="'echo jasfdjj'" --format concise
[p] bash
@ runs bash command
[p] bash modules/bash-command/ params: envvars: at 2017-04-01 22:05:59

jasfdjj
STATUS  SUCCEED
```
Как было:
```
[spigell@dev1 ~]$ sparrow plg run bash --param command="'echo jasfdjj'" 
[p] bash
@ runs bash command
[p] bash modules/bash-command/ params: envvars: at 2017-04-01 22:06:04

jasfdjj
ok      scenario succeeded
STATUS  SUCCEED

```
То есть насколько я вижу, убираются только проверки. 
Хотелось бы, чтобы убиралось вся служебная информация от sparrow. В первом посте есть описание. Возможно стоит сделать еще один тип ("none" или "silent")

**Comment by melezhik** [comment]
Да, я вас понял,  посмотрим, есть ли смысл вводить еще один формат, или можно все это реализовать в рамках `--format concise` .  Надо подумать.

**Comment by melezhik** [comment]
Добавил в  `--format concise`, пробуйте

**Comment by melezhik** [comment]
```
$ sparrow plg run bash --param command="'echo jasfdjj'" --format concise
jasfdjj
```

**Comment by spigell** [comment]
Здравствуйте. Работает как нужно.
Спасибо.
