### ISSUE TITLE
Sparrow task configuration

### ISSUE THREAD

**Issue by spigell** [melezhik/sparrow#14]
Здравствуйте. На текущий момент конфигурация тасков у sparrow при использовании json или yaml не самая удобная. То есть, команда `sparrow task ini` предполагает, что формат будет в Config::General, и если подложить yaml, то данные не подтянутся (Но в тоже время suite.yaml в корне плагина успешно работает). По крайней мере, у меня так. Есть ключ --yaml для тасков, но тогда не очень понятно зачем нужны задачи в таком случае. Ничего не имею против config::general, конечно.
Быть может, имеет смысл как-то заставить работать конфиги в формате json и yaml, когда они создаются комадой `sparrow task ini`, а ключи `--yaml` и `--json` перенести для команды `sparrow plg run`?

**Comment by melezhik** [comment]
Приветствую! 

Можно создать специальное дейтствие `load-config` , для того что бы sparrow учитывал расширение файла, загружая конфигурацию в таск в нужном формате - вместо load-ini который умеет работать только с форматом Config::General

```
$ sparrow task load-config my-task /path/to/config.ini # load Config::General format config
$ sparrow task run project/my-task
$ sparrow task load-config my-task /path/to/config.json # load JSON format config
$ sparrow task run project/my-task
$ sparrow task load-config my-task /path/to/config.yaml # load YAML config
$ sparrow task run project/my-task

```
Мне кажется это примерно то что вы хотите?

**Comment by spigell** [comment]
Новое действие load-config это хорошо (я честно не задумывался, что load_ini тоже расчитан на Config::General), но я немного про другое. Я хотел бы, чтобы при `sparrow task ini`, когда в редакторе открывается файл я мог бы писать туда в том формате, который поддерживает данный плагин (для outthentic это ini, yaml или json). 
То есть:
```
$ sparrow task ini my-tast

main:
  foo: bar
  foo1: bar1

$ sparrow task run project/my-task
```
То есть иметь одну точку входа для конфигурации таски.

**Comment by melezhik** [comment]
На самом деле я подумал, вот как можно решить вашу задачу ( И в принципе мне самому нравится эта фича ). 

Можно модифицировать имеющийся `--ini`  с тем что бы его можно было вызвать с флагом, задающим формат конфигурации. Примеры:

```
$ sparrow task ini project/my-task # используем дефолтный формат -  Config::General
<foo>
 <bar>
    baz 100
 </bar>
</foo> 

$ sparrow task ini project/my-task --format Config::General #  тоже самое что и предыдущий, только задаем формат явно  -  Config::General


$ sparrow task ini project/my-task --format JSON #  задаем формат JSON
{
  "foo" : {
     "bar" : {
       "baz" : 100
      }
   }
}

$ sparrow task ini project/my-task --format YAML #  задаем формат YAML
  foo:
     bar: 
       baz: 100

$ sparrow task ini project/my-task --format JSON #  выдает ошибку Bad JSON!
<foo>
   <bar>
       baz 100
   </bar>
</foo>
```

Что думаете?

**Comment by spigell** [comment]
Да, так хорошо получается.

**Comment by melezhik** [comment]
Пробуйте:
```
cpanm https://github.com/melezhik/outthentic.git
cpanm https://github.com/melezhik/sparrow.git
```

Я сделал еще проще, теперь sparrow сам догадывается о формате конфигурационного файла, не нужны никакие ключи. Формат Config::General перестает быть дефолтным.

Предыдущий пример будет выглядеть так:

```
$ sparrow task ini project/my-task # используем формат -  Config::General
<foo>
 <bar>
    baz 100
 </bar>
</foo> 

$ sparrow task ini project/my-task #  задаем формат JSON
{
  "foo" : {
     "bar" : {
       "baz" : 100
      }
   }
}

$ sparrow task ini project/my-task #  задаем формат YAML
  foo:
     bar: 
       baz: 100

$ sparrow task ini project/my-task #  выдает ошибку bad configuration!
<foo>
   <bar>
       baz 100
   </bar>
</foo>
```


Тоже самое касается функции load_ini:

```
$ sparrow task load_ini system disk-health /etc/plugins/disk.yaml # load from YAML file
$ sparrow task load_ini system disk-health /etc/plugins/disk.json # load from JSON file
$ sparrow task load_ini system disk-health /etc/plugins/disk.conf # load from Config::General file
```

**Comment by spigell** [comment]
Здравствуйте! Да, это действительно то, что я хотел. Спасибо.

Возможно, также можно добавить для sparrow аналогичные ключи strun (--yaml, --ini, --json) для sparrow plg run. 
Но это некритично.
