### ISSUE TITLE
Issue with remote tasks

### ISSUE THREAD

**Issue by spigell** [melezhik/sparrow#15]
Здравствуйте. Если подставить другого юзера в sparrowhub.json
```
[spigell@hammerhead ~]$ cat ~/sparrowhub.json 
{
    "user"  : "melezhik",
	"token" : "..."
}

```
То можно увидеть список его задач

```
[spigell@hammerhead ~]$ sparrow remote task list | head -2
2017-04-07 17:16:34 private	foo_project/t1_task | t1 task
2017-04-07 17:16:32 private	baz_project/baz_task | %comment%
```

Эти задачи не мои. И поставить я их не могу, так sparrowhub отдает 401 http ошибку при установке из-за неправильного токена. Но тем не менее, странное поведение.

Также, в документации по Remote tasks опечатка:
>A shortcut for `sparrow remote task install ... & sparrow task run` is:

>    $ sparrow remote task task run utils/git-setup

```
[spigell@hammerhead ~/my_configs/configs-tmux]$ sparrow remote task task run utils/git-setu
unknown command: task run utils/git-setu at /usr/bin/site_perl/sparrow line 230.
```

**Comment by melezhik** [comment]
1) Ошибка с доступом к списку чужих private remote tasks - поправил и зарелизил.
2) Ошибка в документации поправил - но пока не релизил в CPAN
