### ISSUE TITLE
Problem with sparrow.list

### ISSUE THREAD

**Issue by horse-latitudes** [melezhik/sparrow#17]
Hi.

I'm trying to run '$ sparrow plg search ssh' (that's just an example. I get the same error all over) &
I get 'can't open /home/xxx/sparrow.list to read at /home/xxx/perl5/lib/perl5/Sparrow/Commands/Plugin.pm line 443'
also: 'Sparrow::Commands::Plugin::read_plugin_list() called at /home/xxx/perl5/lib/perl5/Sparrow/Commands/Plugin.pm line 43'
& lastly: 'Sparrow::Commands::Plugin::search_plugins() called at /home/xxx/perl5/bin/sparrow line 34'
Any help appreciated.
Cheers Phil.

**Comment by spigell** [comment]
Greetings. 
Try `sparrow index update` first.
Does file /home/xxx/sparrow.list exist?

**Comment by melezhik** [comment]
Hi! Weird. Try to manually create the file and then run "sparrow plg search ssh"

    touch /home/xxx/sparrow.list

Does it help?

**Comment by horse-latitudes** [comment]
Hi Spigell & melezhik!
I went with both your suggestions but no luck. I still get the same error messages.
also 'sparrow.list' is an empty file & is still so after using 'touch'.

**Comment by spigell** [comment]
Provide plz permission attributes of the file
`stat /home/xxx/sparrow.list`
In normal situation it will be 0644.

**Comment by spigell** [comment]
and look closer on ownership of the file.

**Comment by horse-latitudes** [comment]
'sparrow.list' is actually 0664. Shall I chmod it?

**Comment by horse-latitudes** [comment]
it belongs to me...

**Comment by horse-latitudes** [comment]
this is interesting: without any intervention on my behalf, sparrow commands are now as they should be. Everything works. Bizarre...

**Comment by horse-latitudes** [comment]
thanks to Spigell & melezhik. All good now, sorry for the noise

**Comment by melezhik** [comment]
Hi @horse-latitudes, thanks for feedback. By the way which version of Sparrow do you use?

**Comment by horse-latitudes** [comment]
I installed Sparrow via cpanm yesterday after Gugod, author of perlbrew, mentioned you. HTH...

**Comment by horse-latitudes** [comment]
it was version 0.2.38 according to cpanm...

**Comment by melezhik** [comment]
I have adjusted the code so that the error message is printed when sparrow can't open spl file for read, https://github.com/melezhik/sparrow/commit/d81e67962ebbf79368c6ac11afc06a79fed5af9a , hopefully it will give us more details if error occur again.

**Comment by melezhik** [comment]
Indeed , after thorough investigation, I found it was a bug. As sparrow does not create index file if it does exist, hopefully this commit deal with it. 37b4140c69136bcf3f10feb3507ad64a3448e1bc
