### ISSUE TITLE
Changing all sparrow plugins to be compatible with Outthentic >= 0.3.0

### ISSUE THREAD

**Issue by melezhik** [melezhik/sparrow#18]
Приветствую!

В версии 0.3.0 модуля Outthentic 

1. check files стали необязательными, на данный момент есть много плагинов, где существуют пустые story.check  файлы, теперь в них нет необходимости ...

2. Так же наличие файла meta.txt _перестало означать_, что история не имеет сценария, то что до сих пора называлось мета историей ( технически это означало, что сценарий для такой истории никогда не вызывался, даже если и существовал  ), теперь это просто файл, в котором вы можете положить произвольный текст, который будет выведен в отчете, при выполнение истории.

Я планирую в ближайшее время привести все мои плагины в соответствие с последний версий Outthentic, больше всего будет изменений , связанных с пунктом 1 

Что бы плагины работали, необходимо обновить Outthentic на целевых серверах , насколько для вас ( @Spigell  ) это будет проблематично?

**Comment by spigell** [comment]
Здравствуйте. Да, на днях обновлю, не проблематично.
Изменяйте плагины.

**Comment by melezhik** [comment]
спасибо!

**Comment by melezhik** [comment]
список плагинов с пустыми story.check на SPH
```
archlinux-install
bash-pscp
bash-pssh
bitbucket-repo-list
csvtotable
file-touch-smoke
geo
get-remote-files
git-submodules-update
git-svn-export
goss
group
lvm
meta6-bin
metacpan-api-packages-status
minion-check
minoca-build
minoca-os-test
minoca-pkg-test
mysql-check
mysql-install
nginx-check-example
package-generic
perl6-prove
postgresql-check
postgresql-example
python-sparrow-plugin
rakudo-install
rvm
sendmail
spigell-test
ssh-test1
svn-to-git-submodules
timetest
user
vagrant-vbox-importer
zabbix-hosts
zabbix-hosts-by-alerts
```

**Comment by spigell** [comment]
Я в своих плагинах уберу ненужные check файлы, когда будет следующая версия.

**Comment by melezhik** [comment]
да, конечно. я просто для сведения, все что было вытащил ...
