### ISSUE TITLE
Add changes log on Sparrowhub

### ISSUE THREAD

**Issue by spigell** [melezhik/sparrow#19]
Из [этого](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/sparrowhub/-YzoMHvKXpg/RcS0GDoPAwAJ) поста. Давайте подумаем, может файлик тоже должен быть в виде md документа?

**Comment by melezhik** [comment]
Приветствую!

Появилась кнопка "Changes" для тех плагинов у которых есть файл CHANGES.md , пример - https://sparrowhub.org/info/bash 

Можно обсудить как именно должен именоваться файл изменений ( есть разные вариации ), пока оставляю так - что бы можно было хотя бы посмотреть как это выглядит.

**Comment by melezhik** [comment]
На самом деле добавил support для нескольких _возможных_ наименований для файлы изменений:

`CHANGES.md Changes.md Changelog.md CHANGELOG.md Changelog CHANGELOG`

так что пробуйте
