### ISSUE TITLE
Add yaml support for boxes

### ISSUE THREAD

**Issue by spigell** [melezhik/sparrow#25]
It maybe useful when someone can't use sparrowDo, but need to keep tasks in one file.

**Comment by melezhik** [comment]
проверьте пож-та, примеры в документации

**Comment by spigell** [comment]
Здравствуйте! Спасибо, работает. Единственное, файлы с расширением yml не отрабатывают. 
```
[vagrant@archlinux ~]$ sparrow box run ./test.yml 
sparrow root: [/home/vagrant/sparrow]
mkdir /home/vagrant/sparrow/plugins
unsupported task box spec format: ./test.yml at /usr/share/perl5/site_perl/Sparrow/Commands/TaskBox.pm line 44.
```
Кажется, здесь может быть опечатка - https://github.com/melezhik/sparrow/blob/ffb90a1235290e8bca68cf9d50b854a19bedada4/lib/Sparrow/Commands/TaskBox.pm#L39

**Comment by melezhik** [comment]
поправил

**Comment by spigell** [comment]
Спасибо.

**Comment by melezhik** [comment]
released at v. 0.3.3
