### ISSUE TITLE
SparrowHub trouble

### ISSUE THREAD

**Issue by mcstafford-git** [melezhik/sparrow#28]
I'm trying sparrow for the first time here and may need some guidance, but there's a chance that something's off.

```
$ head sparrow.index
<!DOCTYPE html>
<html>
<head>

  <script src="/js/jquery-1.12.2.min.js"></script>
```

No plugin info shown in response to https://sparrowhub.org/info/perlbrew?v=0.001004, either.

**Comment by melezhik** [comment]
Hi @mcstafford-git ! This is an old sparrowhub site, I don’t own this domain anymore  , it was taken by someone after it was expired, and they made up a fake design pretending the original web site, so don’t use it! This is a fake. 

You should use https://sparrowhub.io instead

HTH

Alexey
