### ISSUE TITLE
Request for python support

### ISSUE THREAD

**Issue by spigell** [melezhik/sparrow#7]
Greetings. Are you planning to add support for python scripts? 
Thanks.

**Comment by melezhik** [comment]
Ahhh, sure! I just awaited someone need it :) so do you?

**Comment by spigell** [comment]
yes, It would be great!

**Comment by melezhik** [comment]
Yeah, will add to my nearest plans. Will let you know later. Thanks for your interest in sparrow.

**Comment by melezhik** [comment]
@Spigell Я почти закончил реализацию поддержки Питона. Ставьте из гитхаба:

```
cpanm https://github.com/melezhik/outthentic.git
```

Или через sparrowdo:

```
$ panda install Sparrowdo::Sparrow::Update
$ sparrowdo --host=$target-host --module_run=Sparrow::Update
```

Примеры сценариев для питона - https://github.com/melezhik/outthentic/tree/master/examples/python

Теперь можно писать плагины на Питоне. Пробуйте.

Из нереализованных функций осталось только `captrures`

**Comment by melezhik** [comment]
Released at Outthentic 0.2.25 -  https://metacpan.org/changes/release/MELEZHIK/Outthentic-0.2.25

**Comment by spigell** [comment]
Спасибо. Обязательно посмотрю, когда разгребу свои дела.
