### ISSUE TITLE
logging in sparrow client

### ISSUE THREAD

**Issue by spigell** [melezhik/sparrow#9]
Здравствуйте. У меня в планах есть создание плагина sparrow для запуска sparrowDO на мастер-хосте, т.е. что-то вроде git pull или puppet agent, так как не всегда целевые хосты включены во время "прогона" через sparrowDO. В связи с этим мне хотелось бы sparrow сам запускался (как это сделано уже не важно) и, что немаловажно, желательно, чтобы он что-то писал куда-нибудь. Мой вопрос именно в логировании. Возможно ли добавить в sparrow какое-то логирование в файл прямо в клиент (хотя бы с указанием времени запуска тестов и выводом результатов теста в читаемом виде из файла без указания цветовых последовательностей)? На текущий момент перенаправление из stdout в файл для сохранения результата работает, но потом смотреть это тяжело, на мой взгляд:
`[spigell@hammerhead ~]$ sparrow plg run df-check > ./sparrow.log
`
Если сделать cat этого файла, то в stdout будет все нормально. Но в less или vim это будет смотрется так:
```
ESC[33m{df-check} ESC[0m
ESC[37mFilesystem                            Size  Used Avail Use% Mounted onESC[0m
ESC[37mdev                                   2.9G     0  2.9G   0% /devESC[0m
ESC[37mrun                                   2.9G  1.2M  2.9G   1% /runESC[0m
ESC[37m/dev/mapper/vg--arch--root-slashroot   25G   22G  2.3G  91% /ESC[0m
ESC[37mtmpfs                                 2.9G   27M  2.9G   1% /dev/shmESC[0m
ESC[37mtmpfs                                 2.9G     0  2.9G   0% /sys/fs/cgroupESC[0m
ESC[37mtmpfs                                 5.0G   64K  5.0G   1% /tmpESC[0m
ESC[37mtmpfs                                 5.0G     0  5.0G   0% /var/tmpESC[0m
ESC[37m/dev/sda1                             194M   90M   94M  49% /bootESC[0m
ESC[37m/dev/mapper/vg--arch--home-spigell     14G  9.5G  3.6G  73% /home/spigellESC[0m
ESC[37m/dev/mapper/vg--arch--home-music      6.8G  5.6G  821M  88% /home/spigell/musicESC[0m
ESC[37m/dev/mapper/vg--arch--home-downloads  9.8G  2.9G  6.4G  31% /home/spigell/downloadsESC[0m
ESC[37m/dev/mapper/vg--arch--home-VMs         26G   24G  512M  98% /home/spigell/VMsESC[0m
ESC[37mtmpfs                                 586M   12K  586M   1% /run/user/1000ESC[0m
ESC[37m/dev/sda3                              15G  5.9G  8.2G  42% /home/spigell/fedora-storESC[0m
ESC[37mOKESC[0m
ESC[32mok       scenario succeededESC[0m
threshhold: 80
ESC[32mok       text match /(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)/ESC[0m
ESC[32mok       enough disk space (0%) on devESC[0m
ESC[32mok       enough disk space (1%) on runESC[0m
ESC[31mnot ok   enough disk space (91%) on /dev/mapper/vg--arch--root-slashrootESC[0m
ESC[32mok       enough disk space (1%) on tmpfsESC[0m
ESC[32mok       enough disk space (0%) on tmpfsESC[0m
ESC[32mok       enough disk space (1%) on tmpfsESC[0m
ESC[32mok       enough disk space (0%) on tmpfsESC[0m
ESC[32mok       enough disk space (49%) on /dev/sda1ESC[0m
ESC[32mok       enough disk space (73%) on /dev/mapper/vg--arch--home-spigellESC[0m
ESC[31mnot ok   enough disk space (88%) on /dev/mapper/vg--arch--home-musicESC[0m
ESC[32mok       enough disk space (31%) on /dev/mapper/vg--arch--home-downloadsESC[0m
ESC[31mnot ok   enough disk space (98%) on /dev/mapper/vg--arch--home-VMsESC[0m
ESC[32mok       enough disk space (1%) on tmpfsESC[0m
ESC[32mok       enough disk space (42%) on /dev/sda3ESC[0m
ESC[31mSTATUS   FAILED (256)
ESC[0m

```
Конечно, можно убрать эти символы из файла через регулярки, оставить только неудачные тесты, но это неудобно.
Как вы считаете, нужно ли логирование? Возможно. что-то удобное есть в sparrowUP, но я честно не вижу смысла мне его ставить.

**Comment by spigell** [comment]
Насчет цвета, я еще раз почитал доку, нашел переменную SPARROW_NO_COLOR.

**Comment by melezhik** [comment]
Приветствую!  Давайте по порядку.

> Насчет цвета, я еще раз почитал доку, нашел переменную SPARROW_NO_COLOR.

Есть еще опция --nocolor

```
sparrow plg run df-check  --nocolor > ./sparrow.log
```

**Comment by melezhik** [comment]
Да и еще, на самом деле, это я казал как запускать плагины в бесцветном через sparrow клиент, вы то хотите их запускать через sparrowdo, тогда там есть такая же опция:

```
sparrowdo  --nocolor
```

**Comment by melezhik** [comment]
вообще у sparrowdo много [опций](https://github.com/melezhik/sparrowdo#sparrowdo-client-command-line-parameters) , все они описаны в документации

**Comment by melezhik** [comment]
> Как вы считаете, нужно ли логирование?

Онo уже есть.
Другой вопрос, что лично для меня пока не стоит задачи запуску _по крону_ sparrow плагинов через sparrowdo на удаленных хостах и дальнейшего разбора логов. 

Обычно мой воркфлоу такой - я запускаю sparrowdo и смотрю что происходит и никак не _накапливаю_ логи для дальнейшей обработки. Судя по всему, у вас другой вариант использования.  

Таким образом,  я не определял каких-то _жестких_ требований к формату логов. Так что - если что-то нужно будет еще пишите - будем обсуждать. 

Да, и кстати сказать, - формат логов sparrow нельзя сказать что произвольный - у него есть определенная структура , описанная в моем блоге - https://sparrowdo.wordpress.com/2017/01/12/sparrowdo-reports/

**Comment by melezhik** [comment]
> SPARROW_NO_COLOR.

да и на всякий случай установка этой переменной влияет только если вы запускаете плагины через sparrow. В любом случае есть опция '--nocolor' , которая работает и для sparrow и для sparrowdo

**Comment by melezhik** [comment]
> Здравствуйте. У меня в планах есть создание плагина sparrow для запуска sparrowDO на мастер-хосте, т.е. что-то вроде git pull или puppet agent, так как не всегда целевые хосты включены во время "прогона" через sparrowDO.

А просто запуск по крону клиента sparrowdo вам не походит? Зачем вам для это отдельный плагин?

**Comment by spigell** [comment]
Да, я читал про отчеты. Про цвет и цветовые последовательности в файле - это не страшно, да. Другое дело, что нет таймштампов. Это надо обдумать еще.

> А просто запуск по крону клиента sparrowdo вам не походит? Зачем вам для это отдельный плагин?

Вы имеете ввиду на мастер-хосте запускать через n времени? Или sparrow на целевом хосте? Первый вариант мне не нравится, потому как неизвестен вопрос: "Куда, Кому?". Не всегда я хочу, чтобы одно и тоже было везде.
Конечно, можно запустить на целевом хосте в кроне что-то вроде этого:

```
ssh $masterhost 'sparrowdo --host=$clienthost --sparrowfile=/path/to/file'
```

Туда можно и лог прикрутить и всякое разное. Тут как минимум нужно узнать ip клиента, чтобы передать, а потом еще чем-то может обрасти. Это получается обыкновенный "коленночный" скрипт. у меня есть такие, строк на 300.
Плагином проще. Например, в баше, чтобы сделать ключи, особенно GNUstyle, нужно использовать внутренний getopt  и делать огромный case на $1 для парсинга. То есть мне надо сделать к нему ключи, а потом по ssh обращаться (и где-то в середине мне надо как-то доставить этот скрипт на целевой хост). Это может быть и удобно (и единственным вариантом), если скрипт запускается standalone в частных ситуациях для диагностики. Но проще написать в самом скрипте `command=$(config command)` и передать sparrow через --param, чем парсить весь ввод. В перле и в питоне может чуть удобней сделано с ключами, но на баше не айс.
Вот как-то так. Кроме того, я все-таки поставил sparrow на одну win станцию под cygwin и не особо уверен в тамошнем кроне.

**Comment by melezhik** [comment]
Я вас понял. Смотрите тут есть важный принципиальный момент. Чисто исторически я сначала разработал sparrow как обычный консольный клиент для запуска плагинов. Я не предполагал запускать его так как вы хотите. Хотя это не проблема конечно-же. 

Потом появился sparrowdo как надстройка над sparrow для _удаленного_ запуска плагинов на серверах с помощью установленного на этих серверах sparrow. Это уже совсем другая история, т.к. в этом случае sparrowdo выступает как полноценный CM инструмент со своим DSL для вызовов плагинов и с концепцией запуска похожей на  ansible (push based)

Теперь, если вам хочется запускать sparrow _как есть_ в стиле pull ( инверсия по сравнению sparrowdo/push ) , почему нет,  но тогда вы немного ограничиваете себя в возможностях ( тех что предоставляет сам sparrowdo ).  Но смотрите сами. Возможно вам будет тогда интересно почитать про [task боксы](https://github.com/melezhik/sparrow#task-boxes-api).  Во общем ваш подход больше смахивает на то, как запускают chef клиента , где клиентом выступает sparrow клиент , а кукбуки - это плагины. 

> Другое дело, что нет таймштампов. Это надо обдумать еще.

Думаю, можно добавить.

**Comment by melezhik** [comment]
> и в питоне может чуть удобней сделано с ключами,

да и на всякий случай поддержка для питона реализована еще не полностью, если что можете посмотреть вот как это [БУДЕТ](https://github.com/melezhik/outthentic) , думаю скоро выкачу, пока вам не горит?

**Comment by spigell** [comment]
> но тогда вы немного ограничиваете себя в возможностях

А можно подробней? Сходу не понимаю. 
Просто pull схема подходит для хостов, которые не всегда доступны (выключены или за NAT находятся) 

Нет, питон не горит, конечно же. Посмотрю на досуге.

**Comment by melezhik** [comment]
ок, тогда давайте резюмируем к чему сводится тикет?

**Comment by melezhik** [comment]
> Просто pull схема подходит для хостов, которые не всегда доступны (выключены или за NAT находятся)

это я понимаю

> А можно подробней? Сходу не понимаю.

ну просто sparrowdo позволяет писать сценарии на Perl6 , абстрагируясь от плагинов как таковых ( ~так где это надо~ по крайней мере, там где вы это хотите - core-dsl, модули   ), и самое главное, позволяет генерить список запускаемых плагинов динамически , исходя из какой-то логики, которая запрограммирована в sparrowdo сценарии.

В случае с запуском просто через sparrow вам придется эту логику ( если я вас правильно понял ) - реализовывать в некотором плагине, причем от задачи к задаче - вам видимо придется писать новый плагин. В-принципе я думаю это нормальный кейс, но как я писал уже я pull схему не рассматривал, единственное что вам может в этом плане пригодится - это такс боксы - возможность описывать списки запускаемых плагинов и их параметров в виде JSON файла и запуск в bulk режиме

**Comment by spigell** [comment]
Я наверно не во всем еще разобрался, но я pull плагином буду также запускать sparrowDO на мастер-хосте, где в sparrowfile также можно будет описывать с помощью core-dsl и perl6. Это будет очень простой скрипт на баше + обертка. Давайте пока оставим эту тему.

Насчет лога:
1) --log-file ключ у sparrow клиента (то есть не надо, чтобы он всегда что-то куда-то писал). Энтот ключ добавляет сам пользователь, если хочет лог.
2) Формат лога: 
date (dd/mm/yy hh:mm) - запустился плагин
Выводить в лог только ошибки. 


Можно конечно и изменить уровель логирования. Например, 3 - нормальный уровель, 5 - дебаг-лог. Но это сейчас не нужно.

**Comment by melezhik** [comment]
Уффффф, кажется сейчас я понял что же вы имели ввиду-))) вчитался ещё раз в ваш первый коммент ,

> Здравствуйте. У меня в планах есть создание плагина sparrow для запуска sparrowDO на ***мастер-хосте****

Прошу прощения , я думал речь идёт про целевой хост , теперь мне понятен ваш кейс

**Comment by melezhik** [comment]
Тогда забудьте все что я _до этого_ вам сказал , это относилось к запуску sparrow напрямую без  Sparrowdo ...

**Comment by melezhik** [comment]
Теперь на счёт логов. Есть вопросы. 

> Насчет лога:
--log-file ключ у sparrow клиента (то есть не надо, чтобы он всегда что-то куда-то писал). Энтот ключ добавляет сам пользователь, если хочет лог.

Вы хотите это ключ так же побрасывать на уровне запуска Sparrowdo ? 

    $ sparrowdo --log-file /path/to/log.txt

Или же это ключ можно указывать только при запуске sparrow клиента ? 

    $ sparrow plg run df-check --log-file /path/to/log.txt 

Разница в том что в первом случае настройка будет применяться _ко всем, запускаемым в рамках сценария плагинам_ , а во втором случае только к одному плагину. 

 
> Формат лога:
date (dd/mm/yy hh:mm) - запустился плагин
Выводить в лог только ошибки.
Можно конечно и изменить уровель логирования. Например, 3 - нормальный уровель, 5 - дебаг-лог. Но это сейчас не нужно.

По формату лога и уровню потом отдельно оговорим , сначала хотел бы получить ответ на первый вопрос.

**Comment by melezhik** [comment]
Да, и ещё одно уточнение к предыдущему моему комментарию.  В том случае когда ключ  --log-file /path/to/ file - параметр sparrowdo , то лог файл очевидно создаётся на мастере, а если ключ  --log-file /path/to/ file - параметр sparrow  клиента ( команда запуска плагина в нашем случае ) ,  то лог файл создаётся на целевом сервере. То есть собствено вопрос , вас какой кейс интересует ?

**Comment by spigell** [comment]
Знаете, хотелось бы иметь лог и для мастера, и для клиента. Но первоначально я подразумевал про клиента, т.е. второй случай. 
Еще один вопрос возник: "Можно ли через sparrowdo отправлять ключи клиенту?" Тот же --verbose или --nocolor?

**Comment by melezhik** [comment]
> Знаете, хотелось бы иметь лог и для мастера, и для клиента. Но первоначально я подразумевал про клиента, т.е. второй случай.

в принципе можно. скажите, а чем все-таки не устраивает просто перенаправление  STDOUT от sparrowdo/sparrow  в определенный файл ( допустим что проблема с бесцветным выводом решена ) ?  Т.е. что вам даст наличие ключа, который будет задавать путь к файлу? 


> Еще один вопрос возник: "Можно ли через sparrowdo отправлять ключи клиенту?" Тот же --verbose или --nocolor?

Нет. Единственный ключ, который сейчас прозрачно передается от sparrowdo к sparrow - это `--nocolor` заставляя sparrow клиент работать в бесцветном режиме.

**Comment by spigell** [comment]
Да всем устраивает в общем-то. Но опять-таки, нет таймштампов выполнения плагина (можно до этого выполнять date какой-нибудь, в файл при обычном перенаправлении сыпется все. 
> Т.е. что вам даст наличие ключа

Ну наличие этого ключа, на мой взгляд, как-то более правильно, чем 
`date && sparrow plg run iptables-ctrl >> /var/log/sparrow.log`

**Comment by melezhik** [comment]
> Да всем устраивает в общем-то. Но опять-таки, нет таймштампов выполнения плагина (можно до этого выполнять date какой-нибудь, в файл при обычном перенаправлении сыпется все.

Как я уже сказал - таймстамп добавлю. Т.е. я как понял таймстап в логе нужен перед началом запуска самого плагина или же в каждой строчке лога? 

> Ну наличие этого ключа, на мой взгляд, как-то более правильно, чем
date && sparrow plg run iptables-ctrl >> /var/log/sparrow.log

Если честно, пока не вижу сильной необходимости в ключе log-file . Давайте так. Я реализую таймстампы - это просто и быстро, вы пока просто будете редиректить ввывод в файлы. Посмотрите как пойдет, если же станет очевидно, что ключ все-таки нужен - можно вернуться к этой задаче?  Так пойдет?

**Comment by spigell** [comment]
Хорошо, давайте отложим.

**Comment by spigell** [comment]
Давайте только в самом начале время добавим.

**Comment by melezhik** [comment]
ок

**Comment by melezhik** [comment]
готово, обновите модуль Outthentic на целевых хостах:
```
cpanm https://github.com/melezhik/outthentic.git
```

Или через sparrowdo:

```
$ panda install Sparrowdo::Sparrow::Update
$ sparrowdo --host=$target-host --module_run=Sparrow::Update

```

**Comment by spigell** [comment]
Да, увидел время запуска в названии плагина
`{timetest}  at 2017-02-02 13:34:51
`
Думаю, неплохо получилось.

**Comment by melezhik** [comment]
предлагаю все-таки не добавлять поддержку логирования в файлы, давайте пока через перенаправление делать, что думаете?

**Comment by spigell** [comment]
Конечно, давайте отложим.
